version: 0
pushHooks:
  - commitMessageRegExp: "Release ((\\d+[.]?){1,2}\\d)\n\n((\\s|\\S)+)"
    releaseTitleTemplate: "Release version {1}"
    releaseTagTemplate: "v{1}"
    releaseBodyTemplate: "{3}"
