name: 'Auto Release'
description: 'Create a release from a commit message.'
author: 'ChanTsune'
inputs:
  commit_message_regexp:
    description: 'A release is created when a message matches this regex.'
    required: true
  release_title_template:
    description: 'The name of the release.'
    required: true
  release_tag_template:
    description: 'tag template.'
    required: true
  release_body_template:
    description: 'Release body template.'
    required: true
  draft:
    description: '`true` to create a draft (unpublished) release, `false` to create a published one. Default: `false`'
    required: false
    default: false
  prerelease:
    description: '`true` to identify the release as a prerelease. `false` to identify the release as a full release. Default: `false`'
    required: false
    default: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'gray-dark'
