name: "Auto Release"

on:
  push:
    branches:
      - '*'
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: ChanTsune/auto-release@master
        with:
          commit_message_regexp: "Release ((\\d+[.]?){1,2}\\d)\n\n((\\s|\\S)+)"
          release_title_template: "version {1}"
          release_tag_template: "v{1}"
          release_body_template: "{3}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
