name: "Test"

on:
  push:
  pull_request:

jobs: 
  run:
    name: "Test"
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Install dependencies
      run: npm install

    - name: run test
      run: npm run test
