name: "Release with commit"

on:
  push:
    branches:
      - feature/*
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - id: create_release
        uses: ChanTsune/release-with-commit@v1.0.0
        with:
          regexp: "Test ((\\s|\\S)+)"
          regexp_options: "us"
          release_name: "version $1"
          tag_name: "v$1"
          body: "$1"
          draft: true
          prerelease: false
        env:
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
      - name: run after release
        env:
          CREATED: '${{ steps.create_release.outputs.id }}'
        run: |
          echo "$CREATED"
